version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: meditrack-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: meditrack
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - meditrack-network

  # Backend API
  backend:
    build: ./backend
    container_name: meditrack-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: mongodb://mongodb:27017/meditrack
      SECRET_KEY: your-secret-key-change-in-production
      ALLOWED_ORIGINS: http://localhost:3000,http://frontend:3000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    networks:
      - meditrack-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: meditrack-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - meditrack-network

volumes:
  mongodb_data:
  backend_uploads:

networks:
  meditrack-network:
    driver: bridge
